pub mod init_bloodtest_booking;
pub mod init_doctor_profile;
pub mod init_gc_booking;
pub mod init_patient_profile;
pub mod init_technician_profile;
pub mod update_bloodtest_report;
pub mod update_gc_report;
pub mod verify_bloodtest_report;
pub mod verify_gc_report;

pub use init_bloodtest_booking::*;
pub use init_doctor_profile::*;
pub use init_gc_booking::*;
pub use init_patient_profile::*;
pub use init_technician_profile::*;
pub use update_bloodtest_report::*;
pub use update_gc_report::*;
pub use verify_bloodtest_report::*;
pub use verify_gc_report::*;
